#!/usr/bin/env bun
/**
 * build.ts — Rent Without Fear
 *
 * Reads content from content/ (Decap CMS managed),
 * renders Mustache templates from src/templates/,
 * outputs static HTML + CSS + JS into dist/
 *
 * Usage:
 *   bun run build          # one-shot build
 *   bun run dev            # watch mode (rebuilds on change)
 */

import fs from 'fs';
import path from 'path';
import Mustache from 'mustache';
import matter from 'gray-matter';
import yaml from 'js-yaml';
import { marked } from 'marked';

// ─── Paths ───────────────────────────────────────────────
const CONTENT_DIR = path.join(import.meta.dir, 'content');
const TEMPLATE_DIR = path.join(import.meta.dir, 'src', 'templates');
const PARTIALS_DIR = path.join(TEMPLATE_DIR, 'partials');
const CSS_DIR = path.join(import.meta.dir, 'src', 'css');
const JS_DIR = path.join(import.meta.dir, 'src', 'js');
const DIST_DIR = path.join(import.meta.dir, 'dist');

// ─── Helpers ─────────────────────────────────────────────

/** Read a YAML file, return parsed object (or empty obj) */
function readYaml(filepath: string): Record<string, any> {
  try {
    const raw = fs.readFileSync(filepath, 'utf8');
    return (yaml.load(raw) as Record<string, any>) || {};
  } catch { return {}; }
}

/** Read all markdown files in a folder, return array sorted by `order` or `date` */
function readCollection(folder: string): Record<string, any>[] {
  const dir = path.join(CONTENT_DIR, folder);
  if (!fs.existsSync(dir)) return [];

  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.md') || f.endsWith('.yml') || f.endsWith('.yaml'))
    .filter(f => f !== '.gitkeep')
    .map(f => {
      const filepath = path.join(dir, f);
      const raw = fs.readFileSync(filepath, 'utf8');

      if (f.endsWith('.yml') || f.endsWith('.yaml')) {
        return (yaml.load(raw) as Record<string, any>) || {};
      }

      const { data, content } = matter(raw);
      // Parse markdown body if present
      if (content && content.trim()) {
        data._body = marked.parse(content.trim());
      }
      data._slug = path.basename(f, path.extname(f));
      return data;
    })
    .sort((a, b) => {
      // Sort by order if present, else by date descending
      if (a.order !== undefined && b.order !== undefined) return a.order - b.order;
      if (a.date && b.date) return new Date(b.date).getTime() - new Date(a.date).getTime();
      return 0;
    });
}

/** Load all Mustache partials from src/templates/partials/ */
function loadPartials(): Record<string, string> {
  const partials: Record<string, string> = {};
  if (!fs.existsSync(PARTIALS_DIR)) return partials;

  fs.readdirSync(PARTIALS_DIR)
    .filter(f => f.endsWith('.mustache'))
    .forEach(f => {
      const name = path.basename(f, '.mustache');
      partials[name] = fs.readFileSync(path.join(PARTIALS_DIR, f), 'utf8');
    });

  return partials;
}

/** Read a file if it exists, else return '' */
function readFileOr(filepath: string, fallback = ''): string {
  try { return fs.readFileSync(filepath, 'utf8'); } catch { return fallback; }
}

// ─── CMS Preview Generator ──────────────────────────────
/**
 * Generates dist/admin/preview.js — registers Decap CMS preview templates
 * that use the same Mustache partials the site uses, so any template change
 * is automatically reflected in the CMS editor preview pane.
 */
function generatePreviewScript(adminDist: string, partials: Record<string, string>) {
  // Escape backticks and backslashes for embedding in JS template literals
  const esc = (s: string) => s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');

  const partialsObj: Record<string, string> = {};
  for (const [name, tpl] of Object.entries(partials)) {
    partialsObj[name] = esc(tpl);
  }

  const script = `
/**
 * Auto-generated by build.ts — do not edit manually.
 * Registers Decap CMS preview templates using the actual Mustache partials.
 */
(function() {
  // Decap CMS v3 exposes these on the window after CMS script loads
  var h = window.h;
  var createClass = window.createClass;

  // Site CSS + fonts for the preview iframe
  CMS.registerPreviewStyle("/style.css");
  CMS.registerPreviewStyle("https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400;0,700;1,400&family=Work+Sans:wght@400;500;600;700&family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap");

  // Embedded Mustache partials (from src/templates/partials/)
  var partials = {
${Object.entries(partialsObj).map(([k, v]) => `    "${k}": \`${v}\``).join(',\n')}
  };

  // Helper: convert Immutable.js entry data to plain JS object
  function entryToJS(entry) {
    var data = entry.getIn(['data']);
    return data && data.toJS ? data.toJS() : (data || {});
  }

  // Helper: render a Mustache template string with data + partials
  function render(template, data) {
    return Mustache.render(template, data, partials);
  }

  // ── Wrap rendered HTML in a styled container ──
  function previewWrap(html) {
    return h('div', { dangerouslySetInnerHTML: { __html: html } });
  }

  // ═══════════════════════════════════════════════════════════
  // Collection: Statistics (ticker item)
  // ═══════════════════════════════════════════════════════════
  CMS.registerPreviewTemplate('statistics', createClass({
    render: function() {
      var d = entryToJS(this.props.entry);
      var tpl = \`
      <section class="ticker" style="position:relative;height:80px;display:flex;align-items:center">
        <div class="ticker-track" style="animation:none">
          <span class="stat">{{#source}}<a href="{{source}}" target="_blank" rel="noopener noreferrer">{{text}}</a>{{/source}}{{^source}}{{text}}{{/source}}</span>
        </div>
      </section>\`;
      return previewWrap(render(tpl, d));
    }
  }));

  // ═══════════════════════════════════════════════════════════
  // Collection: Nav Grid (homepage grid cell)
  // ═══════════════════════════════════════════════════════════
  CMS.registerPreviewTemplate('nav_grid', createClass({
    render: function() {
      var d = entryToJS(this.props.entry);
      var tpl = \`
      <nav class="home-grid" style="display:grid;grid-template-columns:repeat(3,1fr);border-left:1px solid var(--border);border-right:1px solid var(--border)">
        <a class="grid-cell {{#wide}}grid-cell-wide{{/wide}}" style="cursor:default">
          <div class="cell-top">
            <span class="material-symbols-outlined">{{icon}}</span>
            <span class="cell-num">{{cell_number}}</span>
          </div>
          <div>
            <h2>{{title}}</h2>
            <p>{{description}}</p>
          </div>
        </a>
      </nav>\`;
      return previewWrap(render(tpl, d));
    }
  }));

  // ═══════════════════════════════════════════════════════════
  // Collection: Legal Rights (category + cards)
  // Uses the actual partial's section markup
  // ═══════════════════════════════════════════════════════════
  CMS.registerPreviewTemplate('legal_rights', createClass({
    render: function() {
      var d = entryToJS(this.props.entry);
      var tpl = \`
      <div class="kyr-main" style="padding:40px">
        <section class="kyr-section">
          <div class="kyr-section-header">
            <h2>{{category_title}}</h2>
            <p>{{category_description}}</p>
          </div>
          {{#cards}}
          <div class="legal-card">
            <h3>{{title}}</h3>
            <p>{{body}}</p>
            <div class="legal-tag"><span class="material-symbols-outlined" style="font-size:14px">gavel</span> {{legal_ref}}</div>
          </div>
          {{/cards}}
        </section>
      </div>\`;
      return previewWrap(render(tpl, d));
    }
  }));

  // ═══════════════════════════════════════════════════════════
  // Collection: State Laws
  // ═══════════════════════════════════════════════════════════
  CMS.registerPreviewTemplate('state_laws', createClass({
    render: function() {
      var d = entryToJS(this.props.entry);
      d._badge_class = d.status === 'mta' ? 'sw-badge-mta' : d.status === 'old' ? 'sw-badge-old' : 'sw-badge-partial';
      d._badge_text = d.status === 'mta' ? 'MTA adopted' : d.status === 'old' ? 'Older act' : 'In transition';
      var tpl = \`
      <div style="padding:20px">
        <div class="sw-card">
          <div class="sw-card-header">
            <span class="sw-state-name">{{state_name}}</span>
            <span class="sw-badge {{_badge_class}}">{{_badge_text}}</span>
          </div>
          <p class="sw-excerpt">{{excerpt}}</p>
          <div class="sw-links">
            {{#links}}<a class="sw-link" href="{{url}}">{{text}} <span class="material-symbols-outlined" style="font-size:14px;vertical-align:middle">arrow_forward</span></a>{{/links}}
          </div>
        </div>
      </div>\`;
      return previewWrap(render(tpl, d));
    }
  }));

  // ═══════════════════════════════════════════════════════════
  // Collection: Helplines
  // ═══════════════════════════════════════════════════════════
  CMS.registerPreviewTemplate('helplines', createClass({
    render: function() {
      var d = entryToJS(this.props.entry);
      var tpl = \`
      <div style="padding:20px">
        <div class="legal-card">
          <h3 style="font-size:15px">{{title}}</h3>
          <p>{{description}}</p>
          {{#phone}}<div class="legal-tag" style="color:var(--primary);font-family:'Work Sans',sans-serif;font-size:13px">Helpline: <strong>{{phone}}</strong></div>{{/phone}}
          {{#url}}<div class="legal-tag" style="color:var(--info);font-size:13px;font-family:'Work Sans',sans-serif">{{url}}</div>{{/url}}
        </div>
      </div>\`;
      return previewWrap(render(tpl, d));
    }
  }));

  // ═══════════════════════════════════════════════════════════
  // Collection: Stories
  // ═══════════════════════════════════════════════════════════
  CMS.registerPreviewTemplate('stories', createClass({
    render: function() {
      var d = entryToJS(this.props.entry);
      var image = this.props.entry.getIn(['data', 'image']);
      var getAsset = this.props.getAsset;
      d._image_url = image && getAsset ? getAsset(image).toString() : '';
      d._is_danger = d.tag_style === 'danger';
      var tpl = \`
      <div class="stories-grid" style="padding:40px;display:grid;grid-template-columns:repeat(3,1fr);border-left:1px solid var(--border)">
        <div class="story-card {{#featured}}story-card-featured{{/featured}}">
          {{#_image_url}}
          <img class="story-img" src="{{_image_url}}" alt="{{title}}" />
          {{/_image_url}}
          {{^_image_url}}
          <div class="story-img" style="background:linear-gradient(135deg,#1a1a1a,#2a2a2a);display:flex;align-items:center;justify-content:center;aspect-ratio:16/10">
            <span class="material-symbols-outlined" style="font-size:40px;color:var(--border)">{{#placeholder_icon}}{{placeholder_icon}}{{/placeholder_icon}}{{^placeholder_icon}}image{{/placeholder_icon}}</span>
          </div>
          {{/_image_url}}
          <div class="story-content">
            <div class="story-tag {{#_is_danger}}story-tag-danger{{/_is_danger}}">{{tag}}</div>
            <h3>{{title}}</h3>
            <p>{{excerpt}}</p>
            <div class="story-meta"><span>{{city}}</span></div>
          </div>
        </div>
      </div>\`;
      return previewWrap(render(tpl, d));
    }
  }));

  // ═══════════════════════════════════════════════════════════
  // Collection: Journal
  // ═══════════════════════════════════════════════════════════
  CMS.registerPreviewTemplate('journal', createClass({
    render: function() {
      var d = entryToJS(this.props.entry);
      var tpl = \`
      <div style="max-width:600px;padding:20px">
        <div class="legal-card">
          <div style="display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:12px;gap:16px">
            <div>
              {{#tag}}<div style="font-size:10px;font-weight:700;color:var(--primary);letter-spacing:0.12em;text-transform:uppercase;margin-bottom:6px">{{tag}}</div>{{/tag}}
              <h3 style="font-size:18px;font-weight:700;font-family:'Lora',serif">{{title}}</h3>
            </div>
            <span class="material-symbols-outlined" style="color:var(--muted);font-size:28px">mic</span>
          </div>
          <p style="color:#d1d5db;font-size:14px;line-height:1.75">{{description}}</p>
        </div>
      </div>\`;
      return previewWrap(render(tpl, d));
    }
  }));

  // ═══════════════════════════════════════════════════════════
  // Collection: Legal Templates
  // ═══════════════════════════════════════════════════════════
  CMS.registerPreviewTemplate('templates', createClass({
    render: function() {
      var d = entryToJS(this.props.entry);
      var tpl = \`
      <div class="action-left" style="padding:40px;background:#f8f7f5;color:#1a1a1a">
        <div class="template-card">
          <div class="template-card-top">
            <div>
              <h3>{{title}}</h3>
              <p>{{description}}</p>
            </div>
            <span class="material-symbols-outlined">{{icon}}</span>
          </div>
          <button class="btn-download">
            <span class="material-symbols-outlined" style="font-size:18px">download</span> Download PDF Form
          </button>
        </div>
      </div>\`;
      return previewWrap(render(tpl, d));
    }
  }));

  // ═══════════════════════════════════════════════════════════
  // Collection: Wall Posts
  // ═══════════════════════════════════════════════════════════
  CMS.registerPreviewTemplate('wall_posts', createClass({
    render: function() {
      var d = entryToJS(this.props.entry);
      var tpl = \`
      <div style="padding:20px;max-width:400px">
        <div class="wall-card {{#urgent}}wall-card-urgent{{/urgent}}{{^urgent}}wall-card-normal{{/urgent}}">
          {{#urgent}}<div class="urgent-badge">Urgent</div>{{/urgent}}
          <div class="card-location"><span class="material-symbols-outlined" style="font-size:14px">location_on</span> {{location}}</div>
          <div class="card-badge {{#urgent}}card-badge-danger{{/urgent}}">{{issue_type}}</div>
          <p>{{body}}</p>
          <div class="card-footer">
            <button class="upvote-btn"><span class="material-symbols-outlined" style="font-size:18px">arrow_upward</span><span>{{upvotes}}</span></button>
            <button class="share-btn"><span class="material-symbols-outlined" style="font-size:18px">share</span></button>
          </div>
        </div>
      </div>\`;
      return previewWrap(render(tpl, d));
    }
  }));

  // ═══════════════════════════════════════════════════════════
  // Settings: Hero
  // ═══════════════════════════════════════════════════════════
  CMS.registerPreviewTemplate('hero', createClass({
    render: function() {
      var d = entryToJS(this.props.entry);
      var getAsset = this.props.getAsset;
      if (d.hero_bg && getAsset) d._bg_url = getAsset(d.hero_bg).toString();
      var tpl = \`
      <section class="hero" style="position:relative;height:500px;display:flex;flex-direction:column;align-items:center;justify-content:flex-end;padding-bottom:60px;text-align:center;border-bottom:1px solid var(--border)">
        <div class="hero-bg" {{#_bg_url}}style="background-image:linear-gradient(to top,var(--bg) 0%,rgba(26,26,26,0.7) 50%,transparent 100%),url('{{_bg_url}}');background-size:cover;background-position:center"{{/_bg_url}}></div>
        <div class="hero-content" style="position:relative;z-index:1;max-width:900px;padding:0 20px">
          <h1 style="font-size:72px;font-weight:700;line-height:1;margin-bottom:20px;letter-spacing:-0.02em">{{heading_line1}}<br/>{{heading_line2}}</h1>
          <p style="font-size:18px;max-width:600px;margin:0 auto 36px;line-height:1.7;opacity:0.9">{{subheading}}</p>
          <button class="btn-primary">{{cta_text}}</button>
        </div>
      </section>\`;
      return previewWrap(render(tpl, d));
    }
  }));

  // ═══════════════════════════════════════════════════════════
  // Settings: Emergency Banner
  // ═══════════════════════════════════════════════════════════
  CMS.registerPreviewTemplate('emergency_banner', createClass({
    render: function() {
      var d = entryToJS(this.props.entry);
      var tpl = \`
      {{#visible}}
      <div class="emergency-banner">
        <div>
          <strong>{{title}}</strong>
          <p>{{description}}</p>
        </div>
        <button class="btn-primary">{{button_text}}</button>
      </div>
      {{/visible}}
      {{^visible}}
      <div style="padding:40px;text-align:center;color:var(--muted);font-style:italic">Banner is currently hidden</div>
      {{/visible}}\`;
      return previewWrap(render(tpl, d));
    }
  }));

  // ═══════════════════════════════════════════════════════════
  // Settings: Crisis Panel
  // ═══════════════════════════════════════════════════════════
  CMS.registerPreviewTemplate('crisis_panel', createClass({
    render: function() {
      var d = entryToJS(this.props.entry);
      var tpl = \`
      <div class="action-right" style="padding:40px;background:var(--danger);color:#fff">
        <div class="crisis-icon"><span class="material-symbols-outlined" style="font-variation-settings:'FILL' 1">warning</span></div>
        <h2>{{heading}}</h2>
        <div class="donot">{{warning_text}}</div>
        <p class="sub">{{description}}</p>
        {{#contacts}}
        <a class="contact-card" href="{{phone_uri}}">
          <div>
            <div class="contact-label">{{label}}</div>
            <div class="contact-num">{{number}}</div>
          </div>
          <div class="contact-icon"><span class="material-symbols-outlined" style="font-size:22px">{{icon}}</span></div>
        </a>
        {{/contacts}}
      </div>\`;
      return previewWrap(render(tpl, d));
    }
  }));

  // ═══════════════════════════════════════════════════════════
  // Settings: General
  // ═══════════════════════════════════════════════════════════
  CMS.registerPreviewTemplate('general', createClass({
    render: function() {
      var d = entryToJS(this.props.entry);
      var tpl = \`
      <div style="padding:40px">
        <div style="margin-bottom:32px">
          <div style="font-size:11px;font-weight:700;color:var(--muted);letter-spacing:0.15em;text-transform:uppercase;margin-bottom:8px">Site Title</div>
          <h1 style="font-size:36px;font-weight:700">{{site_title}}</h1>
        </div>
        <div style="margin-bottom:32px">
          <div style="font-size:11px;font-weight:700;color:var(--muted);letter-spacing:0.15em;text-transform:uppercase;margin-bottom:8px">Tagline</div>
          <p style="font-size:16px">{{tagline}}</p>
        </div>
        <div style="margin-bottom:32px">
          <div style="font-size:11px;font-weight:700;color:var(--muted);letter-spacing:0.15em;text-transform:uppercase;margin-bottom:8px">NALSA Helpline</div>
          <p style="font-size:20px;font-weight:700">{{nalsa_helpline}}</p>
        </div>
        <div style="margin-bottom:32px">
          <div style="font-size:11px;font-weight:700;color:var(--muted);letter-spacing:0.15em;text-transform:uppercase;margin-bottom:8px">Brand Colors</div>
          <div style="display:flex;gap:12px;margin-top:8px">
            <div style="text-align:center"><div style="width:48px;height:48px;background:{{colors.primary}};border:1px solid var(--border)"></div><div style="font-size:10px;color:var(--muted);margin-top:4px">Primary</div></div>
            <div style="text-align:center"><div style="width:48px;height:48px;background:{{colors.bg}};border:1px solid var(--border)"></div><div style="font-size:10px;color:var(--muted);margin-top:4px">BG</div></div>
            <div style="text-align:center"><div style="width:48px;height:48px;background:{{colors.danger}};border:1px solid var(--border)"></div><div style="font-size:10px;color:var(--muted);margin-top:4px">Danger</div></div>
            <div style="text-align:center"><div style="width:48px;height:48px;background:{{colors.info}};border:1px solid var(--border)"></div><div style="font-size:10px;color:var(--muted);margin-top:4px">Info</div></div>
          </div>
        </div>
        <div>
          <div style="font-size:11px;font-weight:700;color:var(--muted);letter-spacing:0.15em;text-transform:uppercase;margin-bottom:8px">Footer</div>
          <footer style="border-top:1px solid var(--border);padding-top:16px"><p style="font-size:13px;color:var(--muted)">{{footer_text}}</p></footer>
        </div>
      </div>\`;
      return previewWrap(render(tpl, d));
    }
  }));

  console.log('✅ CMS preview templates registered');
})();
`;

  fs.writeFileSync(path.join(adminDist, 'preview.js'), script);
}

// ─── Build ───────────────────────────────────────────────

function build() {
  const startTime = Date.now();
  console.log('\n🔨 Building Rent Without Fear...');

  // 1. Read all content
  const data: Record<string, any> = {
    // Singletons
    settings: readYaml(path.join(CONTENT_DIR, 'settings', 'general.yml')),
    hero: readYaml(path.join(CONTENT_DIR, 'settings', 'hero.yml')),
    emergency_banner: readYaml(path.join(CONTENT_DIR, 'settings', 'emergency_banner.yml')),
    crisis_panel: readYaml(path.join(CONTENT_DIR, 'settings', 'crisis_panel.yml')),

    // Collections
    statistics: readCollection('statistics'),
    nav_grid: readCollection('nav_grid'),
    legal_rights: readCollection('legal_rights'),
    state_laws: readCollection('state_laws'),
    helplines: readCollection('helplines'),
    stories: readCollection('stories'),
    journal: readCollection('journal'),
    templates: readCollection('templates'),
    wall_posts: readCollection('wall_posts'),
  };

  // 2. Computed helpers for Mustache
  // Duplicate statistics for infinite ticker scroll
  data.statistics_doubled = [...data.statistics, ...data.statistics];

  // Add isTagDanger helper for mustache rendering
  data.stories.forEach((s: any) => { s.isTagDanger = s.tag_style === 'danger'; });

  // Separate stories vs research, then featured vs regular
  const storyItems = data.stories.filter((s: any) => s.section !== 'research');
  const researchItems = data.stories.filter((s: any) => s.section === 'research');
  data.featured_story = storyItems.find((s: any) => s.featured) || storyItems[0] || null;
  data.regular_stories = storyItems.filter((s: any) => s !== data.featured_story);
  data.research_stories = researchItems;
  data.has_research = researchItems.length > 0;

  // Helplines by category
  data.legal_helplines = (data.helplines || []).filter((h: any) => h.category !== 'mental_health');
  data.mental_health_helplines = (data.helplines || []).filter((h: any) => h.category === 'mental_health');
  data.has_legal_helplines = data.legal_helplines.length > 0;
  data.has_mental_health_helplines = data.mental_health_helplines.length > 0;

  // Wall posts: separate urgent vs normal
  data.urgent_posts = (data.wall_posts || []).filter((p: any) => p.urgent);
  data.normal_posts = (data.wall_posts || []).filter((p: any) => !p.urgent);
  data.all_wall_posts = [...data.urgent_posts, ...data.normal_posts];
  data.has_community_posts = (data.wall_posts || []).some((p: any) => p.community);

  // State laws: serialize as JSON for the JS state widget
  data.state_laws_json = JSON.stringify(data.state_laws || []);

  // Sidebar links from legal_rights
  data.sidebar_links = (data.legal_rights || []).map((cat: any, i: number) => ({
    ...cat,
    active_class: i === 0 ? 'active' : '',
  }));

  // Has checks for conditionals
  data.has_statistics = data.statistics.length > 0;
  data.has_nav_grid = data.nav_grid.length > 0;
  data.has_legal_rights = data.legal_rights.length > 0;
  data.has_stories = data.stories.length > 0;
  data.has_journal = data.journal.length > 0;
  data.has_templates = data.templates.length > 0;
  data.has_wall_posts = data.wall_posts.length > 0;
  data.has_helplines = data.helplines.length > 0;
  data.has_emergency_banner = data.emergency_banner && data.emergency_banner.visible !== false;
  data.has_crisis_contacts = data.crisis_panel && data.crisis_panel.contacts && data.crisis_panel.contacts.length > 0;

  // 3. Load templates & partials
  const layoutTemplate = readFileOr(path.join(TEMPLATE_DIR, 'layout.mustache'));
  const partials = loadPartials();

  // 4. Render HTML
  const html = Mustache.render(layoutTemplate, data, partials);

  // 5. Read CSS and JS source files
  const css = readFileOr(path.join(CSS_DIR, 'style.css'));
  const js = readFileOr(path.join(JS_DIR, 'main.js'));

  // 6. Write to dist/
  fs.mkdirSync(DIST_DIR, { recursive: true });
  fs.writeFileSync(path.join(DIST_DIR, 'index.html'), html);
  fs.writeFileSync(path.join(DIST_DIR, 'style.css'), css);
  fs.writeFileSync(path.join(DIST_DIR, 'main.js'), js);

  // Copy admin folder to dist
  const adminDist = path.join(DIST_DIR, 'admin');
  fs.mkdirSync(adminDist, { recursive: true });
  fs.copyFileSync(path.join(import.meta.dir, 'admin', 'index.html'), path.join(adminDist, 'index.html'));
  fs.copyFileSync(path.join(import.meta.dir, 'admin', 'config.yml'), path.join(adminDist, 'config.yml'));

  // Generate CMS preview script with embedded Mustache partials
  generatePreviewScript(adminDist, partials);

  // Copy static assets
  const staticSrc = path.join(import.meta.dir, 'static');
  const staticDist = path.join(DIST_DIR, 'static');
  if (fs.existsSync(staticSrc)) {
    copyDirSync(staticSrc, staticDist);
  }

  const elapsed = Date.now() - startTime;
  console.log(`✅ Built in ${elapsed}ms → dist/`);
  console.log(`   index.html  (${(html.length / 1024).toFixed(1)} KB)`);
  console.log(`   style.css   (${(css.length / 1024).toFixed(1)} KB)`);
  console.log(`   main.js     (${(js.length / 1024).toFixed(1)} KB)`);
}

/** Recursively copy directory */
function copyDirSync(src: string, dest: string) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) copyDirSync(srcPath, destPath);
    else fs.copyFileSync(srcPath, destPath);
  }
}

// ─── Run ─────────────────────────────────────────────────

build();

// Watch mode
if (process.argv.includes('--watch')) {
  const chokidar = await import('chokidar');
  console.log('\n👀 Watching for changes...');

  chokidar.watch([
    path.join(import.meta.dir, 'content', '**', '*'),
    path.join(import.meta.dir, 'src', '**', '*'),
  ], { ignoreInitial: true }).on('all', (event: string, filepath: string) => {
    console.log(`\n📝 ${event}: ${path.relative(import.meta.dir, filepath)}`);
    try { build(); } catch (e: any) { console.error('❌ Build error:', e.message); }
  });
}
